"""Init

Revision ID: dc1452c1db9a
Revises: 
Create Date: 2024-02-25 18:20:52.216429

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dc1452c1db9a'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Groups',
    sa.Column('GroupID', sa.Integer(), nullable=False),
    sa.Column('GroupName', sa.String(length=200), nullable=False),
    sa.PrimaryKeyConstraint('GroupID')
    )
    op.create_table('Teachers',
    sa.Column('TeacherID', sa.Integer(), nullable=False),
    sa.Column('TeacherName', sa.String(length=200), nullable=False),
    sa.PrimaryKeyConstraint('TeacherID')
    )
    op.create_table('Students',
    sa.Column('StudentID', sa.Integer(), nullable=False),
    sa.Column('StudentName', sa.String(length=200), nullable=False),
    sa.Column('GroupID', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['GroupID'], ['Groups.GroupID'], ),
    sa.PrimaryKeyConstraint('StudentID')
    )
    op.create_table('Subjects',
    sa.Column('SubjectID', sa.Integer(), nullable=False),
    sa.Column('SubjectName', sa.String(length=200), nullable=False),
    sa.Column('TeacherID', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['TeacherID'], ['Teachers.TeacherID'], ),
    sa.PrimaryKeyConstraint('SubjectID')
    )
    op.create_table('Grades',
    sa.Column('GradeID', sa.Integer(), nullable=False),
    sa.Column('SubjectID', sa.Integer(), nullable=True),
    sa.Column('StudentID', sa.Integer(), nullable=True),
    sa.Column('Grade', sa.Integer(), nullable=True),
    sa.Column('GradeReceiveDate', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['StudentID'], ['Students.StudentID'], ),
    sa.ForeignKeyConstraint(['SubjectID'], ['Subjects.SubjectID'], ),
    sa.PrimaryKeyConstraint('GradeID')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Grades')
    op.drop_table('Subjects')
    op.drop_table('Students')
    op.drop_table('Teachers')
    op.drop_table('Groups')
    # ### end Alembic commands ###
