# Generated by Django 5.0.3 on 2024-03-16 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=100, verbose_name='Author')),
                ('text', models.TextField(verbose_name='Quote')),
                ('tags', models.CharField(help_text='Split tags with coma(,).', max_length=200, verbose_name='Tag')),
            ],
        ),
    ]
