# Generated by Django 5.0.3 on 2024-03-16 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0005_remove_author_slug_alter_author_born_location_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='slug',
            field=models.SlugField(blank=True, max_length=100, unique=True),
        ),
    ]
