# Generated by Django 5.0.3 on 2024-03-16 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0007_alter_author_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='slug',
        ),
    ]
